-- Run this in the Supabase SQL Editor (Dashboard > SQL Editor > New query)
create table if not exists bookings (
  id bigint generated by default as identity primary key,
  room text not null,
  booking_date date not null,
  slot text not null,
  name text not null,
  email text not null,
  notes text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create index if not exists bookings_room_date_idx on bookings (room, booking_date);
